fix: Improved performance when printing logs in Output Channel
IBM-Cloud/ibm-developer-extension-vscode pull request #39
Opened 2022-04-01 20:21 UTC by Aerex

# Description

When running a dev command through the VSCode command palette it takes longer than usual for the logs to appear in the Output panel. This PR solves this problem by upgrade the `vscode` npm package to 1.64 which fixes the buffering issues that occurs in the Output Channel.

# Callouts
Due to the instability of running the vscode integration tests in travis, the unit tests have been removed in favor of running them locally via the exisint precommit git hook.

# Steps to Reproduce
1. Download the latest version of the IBM Cloud CLI extension if not already
2. Open the Command Palette (Ctrl-Shift-P or F1) and enter the command ibmcloud dev build
3. Verify that it takes longer than a minute for the entire logs to appear in the Ouput Channel

# Solution
1. Prune any containers and images that was built in the **Steps to Reproduce** section
2. Install `vsce` npm package if not already: `npm install -g vsce`
3. Checkout PR branch
4. Run the command `vsce package`
5. Verify vsix package is built successfully
6. Open a starterkit project using VSCode
7. Go to **Extension -> Install From VSIX`** and select vsix file created in step 4
![2022-04-01_15-18](https://user-images.githubusercontent.com/5360960/161335625-a380db81-a8ff-4b7d-8567-d6e62d3b715e.png)
8. Reload VSCode when requested
9. Run `ibmcloud dev build` from Command Palette
10. Verify that performance for logs to appear have improved

2022-04-04 22:22 UTC, Aerex commented
@steveclay @schmidtp0740  I was able to get the unit tests to run successfully in docker. FYI 

Ready for re-review

2022-04-05 15:40 UTC, steveclay approved these changes

2022-04-05 15:41 UTC, steveclay commented
@schmidtp0740 please review the Travis / devops changes before we merge this. 👍

2022-04-06 19:19 UTC, schmidtp0740 requested changes

2022-04-06 19:19 UTC, schmidtp0740 commented on ci/Dockerfile
> +FROM ubuntu:18.04
It would be best to use the redhat UBI images

2022-04-06 19:19 UTC, schmidtp0740 commented on ci/Dockerfile
> +FROM ubuntu:18.04
Could start with https://catalog.redhat.com/software/containers/ubi8/ubi/5c359854d70cc534b3a3784e and then install python/node/etc. This image is always most up to date in the past when it comes to patching vulnerabilities

2022-04-08 19:03 UTC, Aerex commented
@schmidtp0740 Updated docker build to create image using redhat UBI. Ready for re-review. FYI @steveclay

2022-04-11 17:35 UTC, schmidtp0740 approved these changes
Nice well done

2022-04-11 18:45 UTC, merged